#!/usr/bin/env bash
# Turnkey testnet setup for a fresh clone: generate + friendbot-fund the four
# Stellar identities Benzo needs, add USDC trustlines, and write a ready-to-use
# .env. The ONE step this can't do for you is acquiring testnet USDC (Circle's
# faucet) — it prints exactly how at the end.
#
# Portable to macOS bash 3.2 (no associative arrays).
#
# Usage:
#   bash scripts/setup-testnet-env.sh            # writes ./.env (refuses to clobber)
#   OUT=/tmp/benzo.env bash scripts/setup-testnet-env.sh
#   PREFIX=benzo KEY_NET=testnet bash scripts/setup-testnet-env.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${OUT:-.env}"
PREFIX="${PREFIX:-benzo}"
KEY_NET="${KEY_NET:-testnet}"
PASSPHRASE="Test SDF Network ; September 2015"
RPC="https://soroban-testnet.stellar.org"
HORIZON="https://horizon-testnet.stellar.org"
FRIENDBOT="https://friendbot.stellar.org"
USDC_CODE="${USDC_CODE:-USDC}"
USDC_ISSUER="${USDC_ISSUER:-GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5}"
# Classic ops (change-trust) submit via RPC and need the passphrase explicitly.
export STELLAR_NETWORK_PASSPHRASE="$PASSPHRASE"

say() { echo "==> $*" >&2; }

if [ -e "$OUT" ]; then
  say "REFUSING to overwrite existing $OUT (it may hold the keys that own your deployed contracts)."
  say "  Set OUT=/path/to/new.env to write elsewhere, or delete/rename $OUT first."
  exit 1
fi
command -v stellar >/dev/null || { say "stellar CLI not found (need 25+)"; exit 1; }

# Generate (if needed) + fund an identity. Echoes "PUBLIC SECRET" on stdout;
# all human-readable progress goes to stderr so the caller can capture cleanly.
mkid() {
  local role="$1" id="${PREFIX}-$1" p s
  if stellar keys address "$id" >/dev/null 2>&1; then
    say "identity $id exists — reusing"
  else
    say "generating identity $id"
    stellar keys generate "$id" --network "$KEY_NET" >/dev/null 2>&1 || true
  fi
  p=$(stellar keys address "$id" 2>/dev/null) || { say "ERROR: could not read address for $id"; return 1; }
  s=$(stellar keys secret "$id" 2>/dev/null) || { say "ERROR: could not read secret for $id"; return 1; }
  # Fund (XLM) idempotently — dedicated subcommand, friendbot fallback; never fatal.
  stellar keys fund "$id" --network "$KEY_NET" >/dev/null 2>&1 \
    || curl -s "$FRIENDBOT?addr=$p" >/dev/null 2>&1 || true
  say "  $role  $p"
  echo "$p $s"
}

read -r DEPLOYER_PUBLIC DEPLOYER_SECRET < <(mkid deployer)
read -r RELAYER_PUBLIC RELAYER_SECRET < <(mkid relayer)
read -r ANCHOR_DISTRIBUTION_PUBLIC ANCHOR_DISTRIBUTION_SECRET < <(mkid anchor-dist)
read -r ANCHOR_SIGNING_PUBLIC ANCHOR_SIGNING_SECRET < <(mkid anchor-sign)

# USDC trustlines (best-effort; CLI tx syntax varies by version — non-fatal).
for r in deployer relayer anchor-dist; do
  id="${PREFIX}-${r}"
  say "adding USDC trustline for $id (best-effort)"
  stellar tx new change-trust --source "$id" --network "$KEY_NET" \
    --line "${USDC_CODE}:${USDC_ISSUER}" >/dev/null 2>&1 \
    || say "  (trustline not added automatically — add ${USDC_CODE}:${USDC_ISSUER} via the Lab if deploy complains)"
done

RELAYER_AUTH_TOKEN="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"

cat > "$OUT" <<ENV
# Generated by scripts/setup-testnet-env.sh — Stellar testnet, no mainnet keys.
STELLAR_NETWORK=testnet
NETWORK_PASSPHRASE=$PASSPHRASE
SOROBAN_RPC_URL=$RPC
HORIZON_URL=$HORIZON
FRIENDBOT_URL=$FRIENDBOT
USE_TEST_TOKEN=false
USDC_CODE=$USDC_CODE
USDC_ISSUER=$USDC_ISSUER

DEPLOYER_PUBLIC=$DEPLOYER_PUBLIC
DEPLOYER_SECRET=$DEPLOYER_SECRET
RELAYER_PUBLIC=$RELAYER_PUBLIC
RELAYER_SECRET=$RELAYER_SECRET
ANCHOR_DISTRIBUTION_PUBLIC=$ANCHOR_DISTRIBUTION_PUBLIC
ANCHOR_DISTRIBUTION_SECRET=$ANCHOR_DISTRIBUTION_SECRET
ANCHOR_SIGNING_PUBLIC=$ANCHOR_SIGNING_PUBLIC
ANCHOR_SIGNING_SECRET=$ANCHOR_SIGNING_SECRET
RELAYER_AUTH_TOKEN=$RELAYER_AUTH_TOKEN
BENZO_ALLOWED_ORIGINS=http://localhost:5173
ENV

say "wrote $OUT"
say ""
say "NEXT (one manual step — testnet USDC can't be auto-acquired):"
say "  1. Fund the deployer with testnet USDC: $DEPLOYER_PUBLIC"
say "     Circle USDC faucet: https://faucet.circle.com  (select Stellar testnet)"
say "  2. set -a; . $OUT; set +a"
say "  3. bash scripts/deploy-testnet.sh      # or run against the ids already in deployments/testnet.json"
say "  4. cd tests && node e2e/m1-flow.mjs"
